AllCops:
  TargetRubyVersion:
    2.4
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - spec/rails_helper.rb
    - lib/tasks/*
    - node_modules/**/*
    - config/*


Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
